
import type { Metadata } from "next";
import "./globals.css";
import "./styles/custom.css";
import { AuthProvider } from "@/app/contexts/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="bg-white min-h-screen flex items-center justify-center">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
